version: '3.8'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:6.0.1
        hostname: zookeeper
        container_name: zookeeper
        ports:
          - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
        networks:
          - streamer_network
    
    kafka:
        image: confluentinc/cp-kafka:6.0.1
        hostname: kafka
        container_name: kafka
        depends_on:
          - zookeeper
        ports:
          - "29092:29092"
          - "9092:9092"
          - "9101:9101"
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_JMX_PORT: 9101
        networks:
          - streamer_network

    redis:
        image: redis:6.0.9-alpine3.12
        container_name: redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 6379:6379
        volumes:
            - rdata:/usr/share/redis/data
        networks:
          - streamer_network
          
    influxdb:
        image: influxdb:1.8.3
        container_name: influxdb
        ports:
            - 8086:8086
        volumes:
            - influxdata:/usr/share/influxdb/data
        networks:
          - streamer_network            
          
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=es01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
          - streamer_network
          
    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.1
        container_name: kibana
        environment:
            SERVER_NAME: http://kibana:5600
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        ports:
          - 5601:5601
        depends_on:
          - elasticsearch
        networks:
          - streamer_network
          
volumes:
    esdata:
    rdata:
    influxdata:
    
networks:
  streamer_network: