version: '3.8'

services:
  streamer-producer:
    build:
      context: .
      dockerfile: Dockerfile_producer
    networks:
      - streamer_network
  streamer:
    build:
      context: .
      dockerfile: Dockerfile_streamer
    networks:
      - streamer_network
    
networks:
  streamer_network: