FROM openjdk:slim

ADD ./dsplatform-1.0.0-test-jar-with-dependencies.jar framework/dsplatform.jar
#ADD ./resources framework/resources
ADD ./data data

# Run the application:
CMD java -cp framework/dsplatform.jar cea.streamer.ProducerMain kdd-cup-99_23class





