FROM openjdk:slim
COPY --from=python:3.6 / /

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies:
COPY requirements.txt framework/requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install -r framework/requirements.txt

ADD ./streamer-1.0.0-test-jar-with-dependencies.jar framework/streamer.jar
ADD ./src framework/src

# Run the application:
CMD java -cp framework/streamer.jar cea.LauncherMain kdd-cup-99_23class





